### PR TITLE
fix: sort directive ordering on post generation

### LINKED ISSUE #121: fix: generated code is violates "directives_ordering" rule
**Description**

Upon generation, some files violate the "[directives_ordering](https://dart.dev/tools/linter-rules/directives_ordering)" rule. This is because some imports are relative to the user specified `project_name`.

The affected files are:
- lib/src/command_runner.dart
- lib/src/commands/update_command.dart
- test/src/command_runner_test.dart
- test/src/commands/sample_command_test.dart
- test/src/commands/update_command_test.dart

**Steps To Reproduce**

1. Mason make with project name "test_cli".

**Expected Behavior**
There should be no violated rules in the generated code.

**Screenshots**

**Additional Context**

### PR DESCRIPTION
**Pull request by alestiago**
## Status

**READY**

## Description

Resolves #121 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: brick/hooks/post_gen.dart [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+Future<void> run(
+  HookContext context, {
+  @visibleForTesting RunProcess runProcess = Process.run,
+}) async {
+  // Some imports are relative to the user specified package name, hence
+  // we try to fix the import directive ordering after the template has
+  // been generated.
+  //
+  // We only fix for the [directives_ordering](https://dart.dev/tools/linter-rules/directives_ordering)
+  // linter rules, as the other rules should be tackled by the template itself.
```
Comment (alestiago) [inline brick/hooks/post_gen.dart:23]:
```suggestion
  // linter rules, as the other rule should be tackled by the template itself.
```

**Review by erickzanardo — APPROVED** [review]
